### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by assume-breach** [hlldz/pickl3#2]
Hi, not really an issue, but more of a question. I've compiled the tool with Visual Studio 2022 Community edition and used it successfully on Windows machines. However, the tool gets an error on machines that do not have Visual Studio C++ installed on them. I tried compiling with gcc but it errors out. I'm sure I'm not doing something correctly so just wondering what the method is that you used to compile the tool. Thanks!

**Comment by hlldz** [comment]
Hi,

The appropriate Microsoft Visual C++ Redistributable package must be installed on the target system, or you must compile it according to what is installed on the target system. https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

I don't know what error you are getting for GCC but I am using MSVC. So I cannot help with that, sorry.

**Comment by msr8** [comment]
I am trying to compile through gcc and getting the following error:
![image](https://user-images.githubusercontent.com/79649185/203646227-ff0fab65-627a-4dbb-ac9a-b026219de116.png)

Even though I have the ATL tools in visual studio installed
![image](https://user-images.githubusercontent.com/79649185/203646371-1cae9f76-dab6-42b8-badf-712d1a2986cf.png)
![image](https://user-images.githubusercontent.com/79649185/203646413-8dd43607-f4da-4ce5-9a97-00ac8fb4a1dc.png)
